# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\diabetes_predicter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.visualation = QtWidgets.QWidget()
        self.visualation.setObjectName("visualation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.visualation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nnc_label = QtWidgets.QLabel(self.visualation)
        self.nnc_label.setObjectName("nnc_label")
        self.horizontalLayout.addWidget(self.nnc_label)
        self.nnc_fields_1 = QtWidgets.QComboBox(self.visualation)
        self.nnc_fields_1.setObjectName("nnc_fields_1")
        self.horizontalLayout.addWidget(self.nnc_fields_1)
        self.nnc_fields_2 = QtWidgets.QComboBox(self.visualation)
        self.nnc_fields_2.setObjectName("nnc_fields_2")
        self.horizontalLayout.addWidget(self.nnc_fields_2)
        self.nnc_btn = QtWidgets.QPushButton(self.visualation)
        self.nnc_btn.setObjectName("nnc_btn")
        self.horizontalLayout.addWidget(self.nnc_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pca_label = QtWidgets.QLabel(self.visualation)
        self.pca_label.setObjectName("pca_label")
        self.horizontalLayout_2.addWidget(self.pca_label)
        self.pca_btn = QtWidgets.QPushButton(self.visualation)
        self.pca_btn.setObjectName("pca_btn")
        self.horizontalLayout_2.addWidget(self.pca_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nnc_label_3 = QtWidgets.QLabel(self.visualation)
        self.nnc_label_3.setText("")
        self.nnc_label_3.setObjectName("nnc_label_3")
        self.horizontalLayout_3.addWidget(self.nnc_label_3)
        self.nnc_btn_3 = QtWidgets.QPushButton(self.visualation)
        self.nnc_btn_3.setObjectName("nnc_btn_3")
        self.horizontalLayout_3.addWidget(self.nnc_btn_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.tabWidget.addTab(self.visualation, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nnc_label.setText(_translate("MainWindow", "Nearest Neighbors Classification"))
        self.nnc_btn.setText(_translate("MainWindow", "Display"))
        self.pca_label.setText(_translate("MainWindow", "Principal Component Analysis"))
        self.pca_btn.setText(_translate("MainWindow", "Display"))
        self.nnc_btn_3.setText(_translate("MainWindow", "Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualation), _translate("MainWindow", "Visualation"))
